//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include "XamlTypeInfo.g.h"

namespace NativePackage
{
    namespace NativePackage_XamlTypeInfo
    {
        [Windows::Foundation::Metadata::WebHostHidden]
        public ref class XamlMetaDataProvider sealed: ::Windows::UI::Xaml::Markup::IXamlMetadataProvider
        {
        public:
            [Windows::Foundation::Metadata::DefaultOverload]
            virtual ::Windows::UI::Xaml::Markup::IXamlType^ GetXamlType(::Windows::UI::Xaml::Interop::TypeName type)
            {
                return GetXamlType(type.Name);
            }
        
            virtual ::Windows::UI::Xaml::Markup::IXamlType^ GetXamlType(Platform::String^ fullName)
            {
                if(_provider == nullptr)
                {
                    _provider = ref new XamlTypeInfo::InfoProvider::XamlTypeInfoProvider();
                }
                return _provider->GetXamlTypeByName(fullName);
            }
        
            virtual Platform::Array<::Windows::UI::Xaml::Markup::XmlnsDefinition>^ GetXmlnsDefinitions()
            {
                return ref new Platform::Array<::Windows::UI::Xaml::Markup::XmlnsDefinition>(0);
            }
        
        private:
            XamlTypeInfo::InfoProvider::XamlTypeInfoProvider^ _provider;
        };
    }
}


